#!/bin/bash

set -e

SCRIPTS_DIR=/tmp/artifacts
DISTRIBUTION_ZIP="jboss-datagrid-6.5.1-server.zip"
DATAGRID_VERSION="6.5.1"
CVE_PATCH="BZ-1281510.zip"

unzip -q $SCRIPTS_DIR/$DISTRIBUTION_ZIP
unzip -q -o $SCRIPTS_DIR/${CVE_PATCH}
mv jboss-datagrid-$DATAGRID_VERSION-server $JBOSS_HOME

chmod 0755 $JBOSS_HOME
chown -R jboss:root $JBOSS_HOME
chmod -R g+rwX $JBOSS_HOME

